### ISSUE TITLE
Highlight with expand_limits

### ISSUE THREAD

**Issue by jsta** [yutannihilation/gghighlight#112]
I am trying to highlight given an `expand_limits` layer but it throws an error:

```r
d <- data.frame(
  idx = c( 1, 1, 1, 2, 2, 2, 3, 3, 3),
  value = c( 1, 2, 3,10,11,12, 9,10,11),
  category = rep(c("a","b","c"), 3),
  stringsAsFactors = FALSE
)

ggplot(d, aes(idx, y = value, colour = category)) +
  geom_line() +
  expand_limits(x = 0) + 
  gghighlight(max(value) > 10)
```
> Error in merge_mapping(layer, plot_mapping) : 
  No mapping found on this layer!

Is this a duplicate of #65?

**Comment by jsta** [comment]
This code seems to work with the Github version of `gghighlight` but not CRAN.

**Comment by yutannihilation** [comment]
I don't remember when I fixed this... Anyway, thanks for reporting!

**Comment by chamaoskurumi** [comment]
For me the above error persists in `gghighlight` version `0.3.9000`...
